backend:
  name: git-gateway
  branch: main  

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Homepage"
        name: "homepage"
        fields:
          - label: "Page Content"
            name: "body"
            widget: "markdown"
